version: "3.3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - /opt/mariadb:/var/lib/mysql
      - ./init.sh:/init.sh:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./first-host.cnf:/etc/mysql/mariadb.conf.d/90-replication.cnf:ro
    network_mode: host
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: *****
      MARIADB_REPL_USER: repluser
      MARIADB_REPL_PASSWORD: *****
      MASTER_HOST_ADDRESS: x.x.x.x
      TZ: Asia/Ho_Chi_Minh
    logging:
      options:
        max-size: "10m"
        max-file: "3"
